# Generated by Django 4.0.4 on 2022-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Templates', 'Templates'), ('Virtual Environments', 'Virtual Environments'), ('Models', 'Models')], max_length=60)),
                ('courseNumber', models.DecimalField(decimal_places=2, max_digits=10000, max_length=60)),
                ('instructorName', models.CharField(max_length=60)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
    ]
